config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'categories#index'

  resources :categories, only: %i[index create new] do
    resources :images, except: %i[destroy edit update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :images

  validates :title, presence: { message: 'Title is required' },
                    uniqueness: { message: 'Current title already exist' }

  default_scope -> { order(created_at: :desc) }
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :attachment, AttachmentUploader

  belongs_to :category
  belongs_to :main_image, class_name: "Image", optional: true

  has_many :sub_images, class_name: "Image", foreign_key: "main_image_id"

  validates_presence_of :attachment

  validate :check_sub_image_type, :check_sub_image_size, if: ->(obj) { obj.main_image_id.present? }

  default_scope -> { order(created_at: :desc) }

  def check_sub_image_type
    original_type = self.main_image.attachment.content_type

    if self.attachment.content_type != original_type
      errors.add(:base, "Uploaded image should have same type: #{ original_type.split("/").last }")
    end
  end

  def check_sub_image_size
    origin_ratio = (self.main_image.attachment.width.to_f / self.main_image.attachment.height.to_f).round(2)
    sub_ratio = (self.attachment.width.to_f / self.attachment.height.to_f).round(2)

    unless (sub_ratio * 100 / origin_ratio).between?(95, 105)
      errors.add(:base, "Uploaded image should have same ratio: #{ origin_ratio }")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = 'Category was successfully created'
      redirect_to categories_path
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:title)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show]
  before_action :set_current_category, only: %i[index new create]

  def index
    @images = @current_category.images.where(main_image_id: nil)
  end

  def show;  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    if @image.save
      flash[:success] = 'Image was successfully created'
      ActionCable.server.broadcast "image_channel",
                                   content: @image
      redirect_to category_images_path
    else
      @main_image_id = params[:image][:main_image_id]
      render :new
    end
  end

  private

  def set_image
    @image = Image.find(params[:id])
  end

  def set_current_category
    @current_category ||= Category.find_by_id(params[:category_id])
  end

  def image_params
    params.require(:image).permit(:main_image_id, :category_id, :attachment, :attachment_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<div class="wrapper">
  <div class="header">
    <h1>Categories</h1>
  </div>

  <div>
    <% if @categories.blank? %>
      <h1>No categories created before</h1>
    <% else %>
      <% @categories.each do |category| %>
        <div>
          <h3><%= category.title %></h3>
          <a href="<%= category_images_path(category.id) %>">Show</a>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="navbar">
    <a href="<%= new_category_path %>" class="btn">New Category</a>
  </div>
</div>

app/views/categories/new.html.erb
<%= form_with(model: @category, local: true) do |f| %>
  <div class="wrapper">
    <div class="header">
      <h3 class="text">New category</h3>
      <a href="<%= categories_path %>" class="btn pull_right">Back</a>
    </div>

    <div>
      <%= f.text_field :title, class:"text_field", required: "required", placeholder: "Title name" %>
    </div>

    <% if @category.errors.any? %>
      <div class="error_message">
        <% @category.errors.full_messages.each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
    <% end %>

    <div>
      <input type="submit" value="Create category" />
    </div>
  </div>
<% end %>

app/views/images/index.html.erb
<header class="header">
  <h1><%= @current_category.title %></h1>
</header>

<main>
  <div class="container">
    <% if @images.blank? %>
      <h1>No images added before</h1>
    <% else %>
      <% @images.each do |image| %>
        <div class="category-wrapper hovered">
          <%= image_tag image.attachment.thumb.url, class: "image", alt: image.attachment.identifier %>
          <a href="<%= category_image_path(@current_category.id, image.id) %>" class="category-show">Show</a>
        </div>
      <% end %>
    <% end %>
  </div>
</main>

<div class="navbar">
  <a href="<%= categories_path %>" class="btn">Back</a>
  <a href="<%= new_category_image_path %>" class="btn">New Image</a>
</div>

app/views/images/new.html.erb
<%= form_with(model: @image, url: category_images_path(main_image_id: @main_image_id), local: true) do |f| %>
  <div class="wrapper">
    <div class="header">
      <h3 class="text">New Image for <%= @current_category.title %></h3>
      <a href="<%= category_images_path %>" class="btn pull_right">Back</a>
    </div>

    <div class="main_form">
      <%= f.file_field :attachment, required: "required" %>
      <%= f.hidden_field :attachment_cache %>

      <% main_image = params[:main_image_id] || @main_image_id %>
      <%= f.hidden_field :main_image_id, value: main_image if main_image %>
      <%= f.hidden_field :category_id, value: @current_category.id %>
    </div>

    <% if @image.errors.any? %>
      <div class="error_message">
        <% @image.errors.full_messages.each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
    <% end %>

    <div>
      <input type="submit" value="Upload file" />
    </div>
  </div>
<% end %>

app/views/images/show.html.erb
<main>
  <div class="container">
    <div class="category-wrapper">
      <%= image_tag @image.attachment.thumb.url, class: "image", alt: @image.attachment.identifier %>
    </div>

    <% @image.sub_images.each do |sub_im| %>
      <div class="category-wrapper">
        <%= image_tag sub_im.attachment.thumb.url, class: "image", alt: sub_im.attachment.identifier %>
      </div>
    <% end %>
  </div>
</main>
<p>

<div class="navbar">
  <a href="<%= category_images_path %>" class="btn">Back</a>
  <a href="<%= new_category_image_path(main_image_id: @image.id) %>" class="btn">Add a similar picture</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageUploader</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>